### PR TITLE
Survey result

### LINKED ISSUE #61: Add images for survey
- [x] adds images for the survey 

- [x] adds images for the results page

### PR DESCRIPTION
**Pull request by MichaelEWalker87**
### This PRs additions:

Adds the files for the result images 
note that some of these files such as modern will need to be moved to the back end 
The files are available in web/public/images/Survey right now all but final need to go to the back end for scoring
 
### Reviewer starting point: 

The user should be able to see most addition in 
web/public/images/Survey
 
### How to manually test:  

This can be tested by going to the file path and verifying that the images and files are able to load  

### background context:  

 This was to provide Survey results as well as survey items for the user to select 

### Relevant tickets: 

 closes: #61 

### Screenshots:

none at this time  

### Questions: 

none at this time

### CODE REVIEW

**Comment by lkriffell** [comment]
Thanks for collecting all these images! BE has some questions regarding the fact that not all of the images are clothes (which we can discuss tomorrow)

**Review by lkriffell — APPROVED** [review]
Looks good to me. I don't know what your code is really doing but once an FE approves and you rebase your commits I'd say good to go!

**Comment by bretm9** [comment]
Before we merge this we should consolidate the photos, and also remove the code annotations existing on the following files:
* `code/web/src/modules/crate/List.js`
* `code/web/src/setup/client/App.js`
* `code/web/src/setup/client/index.js`
* `code/web/src/setup/routes/index.js`
* `code/web/src/setup/routes/result.js`

**Comment by hashmaster3k** [comment]
Closed per group conversation

**Pull request closed without merging**
